// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiamondShop.Data.Models;

public partial class Diamond
{
    public string DiamondId { get; set; }

    public string Name { get; set; }

    public string Color { get; set; }

    public string Clarity { get; set; }

    public decimal? Carat { get; set; }

    public string Cut { get; set; }

    public string CertificateScan { get; set; }

    public decimal? Cost { get; set; }

    public int? AmountAvailable { get; set; }

    public string CategoryId { get; set; }

    public string ImageUrl { get; set; }

    public DateOnly? DateAcquired { get; set; }

    public string CertifyingAuthority { get; set; }

    public string Polish { get; set; }

    public string Symmetry { get; set; }

    public string Fluorescence { get; set; }

    public virtual Productcategory Category { get; set; }

    public virtual ICollection<Orderdetail> OrderdetailMainDiamonds { get; set; } = new List<Orderdetail>();

    public virtual ICollection<Orderdetail> OrderdetailSubDiamonds { get; set; } = new List<Orderdetail>();
}