// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiamondShop.Data.Models;

public partial class Orderdetail
{
    public string OrderDetailId { get; set; }

    public string OrderId { get; set; }

    public decimal LineTotal { get; set; }

    public string MainDiamondId { get; set; }

    public string ShellId { get; set; }

    public string SubDiamondId { get; set; }

    public int Quantity { get; set; }

    public decimal UnitWeight { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal DiscountPercentage { get; set; }

    public string Note { get; set; }

    public virtual Diamond MainDiamond { get; set; }

    public virtual Order Order { get; set; }

    public virtual Shell Shell { get; set; }

    public virtual Diamond SubDiamond { get; set; }
}