// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiamondShop.Data.Models;

public partial class Productcategory
{
    public string CategoryId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string IconUrl { get; set; }

    public string PromotionImageUrl { get; set; }

    public bool? IsFeatured { get; set; }

    public string PromotionalTagline { get; set; }

    public int? ProductAmount { get; set; }

    public string CareInstructions { get; set; }

    public decimal? MinimumPrice { get; set; }

    public decimal? MaximumPrice { get; set; }

    public virtual ICollection<Diamond> Diamonds { get; set; } = new List<Diamond>();

    public virtual ICollection<Shell> Shells { get; set; } = new List<Shell>();
}