// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiamondShop.Data.Models;

public partial class Shell
{
    public string ShellId { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public int AmountAvailable { get; set; }

    public string Description { get; set; }

    public string Style { get; set; }

    public string Metal { get; set; }

    public decimal? Weight { get; set; }

    public string DiamondShape { get; set; }

    public int? TotalDiamonds { get; set; }

    public string CategoryId { get; set; }

    public string ImageUrl { get; set; }

    public virtual Productcategory Category { get; set; }

    public virtual ICollection<Orderdetail> Orderdetails { get; set; } = new List<Orderdetail>();
}